import { useEffect, useMemo, useState } from "react";
import { supabase } from "../supabase";
import { calculateQuoteLandedCost } from "../domain/sourcingIntelligence";
import {
  addPurchaseOrderItem,
  createPurchaseOrder,
  deletePurchaseOrderItem,
  listPurchaseOrderItems,
  listPurchaseOrders,
  updatePurchaseOrder,
} from "../services/purchaseOrderRepository";

const C={ink:"#20251F",olive:"#858C38",oliveDark:"#747B31",green:"#4D7D57",red:"#B65145",muted:"#647062",border:"rgba(50,56,42,.12)",soft:"#F3F4EF"};
const money=v=>v===null||v===undefined||Number.isNaN(Number(v))?"—":Number(v).toLocaleString("en-CA",{style:"currency",currency:"CAD",maximumFractionDigits:2});
const usd=v=>v===null||v===undefined||Number.isNaN(Number(v))?"—":Number(v).toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2});
const input={width:"100%",boxSizing:"border-box",border:`1px solid ${C.border}`,borderRadius:10,padding:"9px 10px",fontSize:13,background:"#fff",color:C.ink};
const btn=(primary=false)=>({border:primary?0:`1px solid ${C.border}`,background:primary?"linear-gradient(180deg,#929A44,#747B31)":"#fff",color:primary?"#fff":C.ink,borderRadius:10,padding:"9px 12px",fontWeight:800,fontSize:13,cursor:"pointer"});
const poRef=()=>`PO-${new Date().toISOString().slice(0,10).replaceAll("-","")}`;
const Field=({label,children})=><label style={{display:"grid",gap:5,fontSize:12,fontWeight:750,color:C.muted}}>{label}{children}</label>;

function moqNumber(text){const m=String(text||"").match(/\d+/);return m?Number(m[0]):null;}

export default function BuyingDecisionWorkspace(){
  const [loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState("");
  const [orders,setOrders]=useState([]),[suppliers,setSuppliers]=useState([]),[products,setProducts]=useState([]),[quotes,setQuotes]=useState([]),[items,setItems]=useState([]);
  const [selectedId,setSelectedId]=useState("");
  const [form,setForm]=useState({poRef:poRef(),supplierId:"",status:"Draft",orderDate:"",expectedDeliveryDate:"",currency:"USD",usdCadRate:"1.38",incoterm:"",paymentTerms:"",notes:""});
  const [itemForm,setItemForm]=useState({productId:"",quoteId:"",quantity:"1",targetSellPriceCad:"",notes:""});

  const load=async()=>{setLoading(true);setError("");try{const [po,{data:s,error:se},{data:p,error:pe},{data:q,error:qe}]=await Promise.all([listPurchaseOrders(),supabase.from("suppliers").select("*").order("sup_id"),supabase.from("products").select("*").order("sku_id"),supabase.from("quotes").select("*").order("created_at",{ascending:false})]);if(se||pe||qe)throw new Error((se||pe||qe).message);setOrders(po);setSuppliers(s||[]);setProducts(p||[]);setQuotes(q||[]);}catch(e){setError(e?.message||"Unable to load buying decisions.");}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  useEffect(()=>{if(!selectedId){setItems([]);return;}const o=orders.find(x=>x.id===selectedId);if(o)setForm({poRef:o.po_ref,supplierId:o.supplier_id,status:o.status,orderDate:o.order_date||"",expectedDeliveryDate:o.expected_delivery_date||"",currency:o.currency||"USD",usdCadRate:String(o.usd_cad_rate||1.38),incoterm:o.incoterm||"",paymentTerms:o.payment_terms||"",notes:o.notes||""});listPurchaseOrderItems(selectedId).then(setItems).catch(e=>setError(e?.message||"Unable to load PO items."));},[selectedId,orders]);

  const selectedSupplier=suppliers.find(s=>s.id===form.supplierId);
  const eligibleQuotes=quotes.filter(q=>(!form.supplierId||q.supplier_id===form.supplierId)&&(!itemForm.productId||q.product_id===itemForm.productId));
  const selectedProduct=products.find(p=>p.id===itemForm.productId);
  const selectedQuote=quotes.find(q=>q.id===itemForm.quoteId);

  useEffect(()=>{if(!selectedQuote)return;const p=products.find(x=>x.id===selectedQuote.product_id);setItemForm(f=>({...f,productId:selectedQuote.product_id,targetSellPriceCad:String(p?.target_sell_price_cad??p?.market_reference_cad??"")}));},[selectedQuote,products]);

  const totals=useMemo(()=>{let merchandiseCad=0,landed=0,revenue=0,units=0;for(const i of items){const q=Number(i.quantity||0);units+=q;merchandiseCad+=(Number(i.unit_price_usd||0)*Number(form.usdCadRate||1))*q;landed+=Number(i.landed_cost_per_unit_cad||0)*q;revenue+=Number(i.target_sell_price_cad||0)*q;}const margin=revenue>0?(revenue-landed)/revenue*100:null;return{units,merchandiseCad,landed,revenue,margin,profit:revenue-landed};},[items,form.usdCadRate]);

  const createNew=async()=>{if(!form.supplierId)return setError("Select a supplier before creating a buying decision.");try{const created=await createPurchaseOrder(form);await load();setSelectedId(created.id);setMessage("Buying decision created as a draft.");}catch(e){setError(e?.message||"Unable to create buying decision.");}};
  const save=async()=>{try{if(!selectedId)return createNew();await updatePurchaseOrder(selectedId,form);await load();setMessage("Buying decision updated.");}catch(e){setError(e?.message||"Unable to update buying decision.");}};
  const addItem=async()=>{if(!selectedId||!itemForm.productId)return;try{const quote=selectedQuote;const landed=quote?calculateQuoteLandedCost(quote):null;const product=products.find(p=>p.id===itemForm.productId);await addPurchaseOrderItem({purchaseOrderId:selectedId,productId:itemForm.productId,quoteId:itemForm.quoteId,quantity:itemForm.quantity,moqText:quote?.moq||null,supplierSku:quote?.supplier_sku||null,unitPriceUsd:quote?.unit_price??null,landedCostPerUnitCad:landed?.totalCad??null,targetSellPriceCad:itemForm.targetSellPriceCad||product?.target_sell_price_cad||product?.market_reference_cad||null,notes:itemForm.notes});setItems(await listPurchaseOrderItems(selectedId));setItemForm({productId:"",quoteId:"",quantity:"1",targetSellPriceCad:"",notes:""});setMessage("Item added with current quote and landed-cost snapshot.");}catch(e){setError(e?.message||"Unable to add item.");}};
  const removeItem=async(id)=>{try{await deletePurchaseOrderItem(id);setItems(await listPurchaseOrderItems(selectedId));}catch(e){setError(e?.message||"Unable to remove item.");}};

  return <div style={{minHeight:"100vh",background:C.soft,color:C.ink}}>
    <div style={{background:"linear-gradient(180deg,#11130F,#20251F)",color:"#fff",padding:"24px 32px"}}><div style={{maxWidth:1560,margin:"0 auto"}}><div style={{color:"#B6BE59",fontSize:12,fontWeight:850,letterSpacing:1.4,textTransform:"uppercase"}}>Costa Gear</div><h1 style={{margin:"4px 0 0",fontSize:30}}>Buying Decisions & Purchase Orders</h1><div style={{color:"#C9CFC4",fontSize:13,marginTop:5}}>Turn sourcing recommendations into planned orders while preserving the commercial snapshot used for the decision.</div></div></div>
    <div style={{maxWidth:1560,margin:"0 auto",padding:"22px 32px 44px",display:"grid",gap:16}}>
      {error&&<div style={{background:"#FFF1EF",color:C.red,borderRadius:10,padding:12}}>{error}</div>}{message&&<div style={{background:"#EDF7EE",color:C.green,borderRadius:10,padding:12}}>{message}</div>}
      {loading?<div style={{padding:40,textAlign:"center",color:C.muted}}>Loading buying decisions…</div>:<>
        <div style={{display:"grid",gridTemplateColumns:"300px 1fr",gap:16,alignItems:"start"}}>
          <div style={{background:"white",border:`1px solid ${C.border}`,borderRadius:16,padding:14,display:"grid",gap:9}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><strong>Buying Decisions</strong><button style={btn()} onClick={()=>{setSelectedId("");setItems([]);setForm({poRef:`${poRef()}-${orders.length+1}`,supplierId:"",status:"Draft",orderDate:"",expectedDeliveryDate:"",currency:"USD",usdCadRate:"1.38",incoterm:"",paymentTerms:"",notes:""});}}>New</button></div>{orders.map(o=>{const s=suppliers.find(x=>x.id===o.supplier_id);return <button key={o.id} onClick={()=>setSelectedId(o.id)} style={{textAlign:"left",border:`1px solid ${selectedId===o.id?C.olive:C.border}`,background:selectedId===o.id?"#F8FAF0":"#fff",borderRadius:10,padding:10,cursor:"pointer"}}><div style={{fontWeight:850}}>{o.po_ref}</div><div style={{fontSize:11,color:C.muted,marginTop:3}}>{o.status} · {s?.name||"Supplier"}</div></button>})}</div>
          <div style={{display:"grid",gap:16}}>
            <div style={{background:"#fff",border:`1px solid ${C.border}`,borderRadius:16,padding:16}}><div style={{fontSize:17,fontWeight:850,marginBottom:12}}>{selectedId?"Buying Decision Details":"Create Buying Decision"}</div><div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:10}}>
              <Field label="PO / Decision Ref"><input style={input} value={form.poRef} disabled={!!selectedId} onChange={e=>setForm(f=>({...f,poRef:e.target.value}))}/></Field><Field label="Supplier"><select style={input} value={form.supplierId} onChange={e=>setForm(f=>({...f,supplierId:e.target.value}))}><option value="">Select supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.sup_id} — {s.name}</option>)}</select></Field><Field label="Status"><select style={input} value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value}))}>{["Draft","Planned","Approved","Ordered","Partially Received","Received","Cancelled"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="USD/CAD"><input style={input} type="number" step="0.0001" value={form.usdCadRate} onChange={e=>setForm(f=>({...f,usdCadRate:e.target.value}))}/></Field>
              <Field label="Order Date"><input style={input} type="date" value={form.orderDate} onChange={e=>setForm(f=>({...f,orderDate:e.target.value}))}/></Field><Field label="Expected Delivery"><input style={input} type="date" value={form.expectedDeliveryDate} onChange={e=>setForm(f=>({...f,expectedDeliveryDate:e.target.value}))}/></Field><Field label="Incoterm"><input style={input} value={form.incoterm} onChange={e=>setForm(f=>({...f,incoterm:e.target.value}))}/></Field><Field label="Payment Terms"><input style={input} value={form.paymentTerms} onChange={e=>setForm(f=>({...f,paymentTerms:e.target.value}))}/></Field>
            </div><Field label="Notes"><input style={input} value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></Field><div style={{marginTop:12}}><button style={btn(true)} onClick={save}>{selectedId?"Save Decision":"Create Draft"}</button></div></div>

            {selectedId&&<><div style={{display:"grid",gridTemplateColumns:"repeat(5,minmax(0,1fr))",gap:10}}>{[["Units",totals.units],["Merchandise Investment",money(totals.merchandiseCad)],["Landed Investment",money(totals.landed)],["Projected Revenue",money(totals.revenue)],["Projected Margin",totals.margin===null?"—":`${totals.margin.toFixed(1)}%`]].map(([l,v])=><div key={l} style={{background:"#fff",border:`1px solid ${C.border}`,borderRadius:14,padding:14}}><div style={{fontSize:11,color:C.muted,fontWeight:750}}>{l}</div><div style={{fontSize:21,fontWeight:850,marginTop:5}}>{v}</div></div>)}</div>
              <div style={{background:"#fff",border:`1px solid ${C.border}`,borderRadius:16,padding:16}}><div style={{fontSize:17,fontWeight:850,marginBottom:10}}>Add Product</div><div style={{display:"grid",gridTemplateColumns:"2fr 2fr .7fr 1fr auto",gap:8,alignItems:"end"}}><Field label="Product"><select style={input} value={itemForm.productId} onChange={e=>setItemForm(f=>({...f,productId:e.target.value,quoteId:"",targetSellPriceCad:String(products.find(p=>p.id===e.target.value)?.target_sell_price_cad??products.find(p=>p.id===e.target.value)?.market_reference_cad??"")}))}><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku_id} — {p.name}</option>)}</select></Field><Field label="Supplier Quote"><select style={input} value={itemForm.quoteId} onChange={e=>setItemForm(f=>({...f,quoteId:e.target.value}))}><option value="">No quote snapshot</option>{eligibleQuotes.map(q=><option key={q.id} value={q.id}>{q.quote_date||"No date"} · {usd(q.unit_price)} · MOQ {q.moq||"—"}</option>)}</select></Field><Field label="Qty"><input style={input} type="number" min="1" value={itemForm.quantity} onChange={e=>setItemForm(f=>({...f,quantity:e.target.value}))}/></Field><Field label="Target Sell CAD"><input style={input} type="number" value={itemForm.targetSellPriceCad} onChange={e=>setItemForm(f=>({...f,targetSellPriceCad:e.target.value}))}/></Field><button style={{...btn(true),height:38}} onClick={addItem}>Add</button></div>{selectedQuote&&<div style={{fontSize:11,color:C.muted,marginTop:8}}>Snapshot preview: unit {usd(selectedQuote.unit_price)} · landed {money(calculateQuoteLandedCost(selectedQuote)?.totalCad)} · MOQ {selectedQuote.moq||"—"}</div>}</div>
              <div style={{background:"#fff",border:`1px solid ${C.border}`,borderRadius:16,padding:16,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:1150,fontSize:12}}><thead><tr style={{background:"#F5F7F1"}}>{["SKU","Product","Qty","MOQ","Unit USD","Landed / Unit","Target Sell","Landed Investment","Revenue","Margin",""].map(h=><th key={h} style={{textAlign:"left",padding:9,color:C.muted,borderBottom:`1px solid ${C.border}`}}>{h}</th>)}</tr></thead><tbody>{items.map(i=>{const p=products.find(x=>x.id===i.product_id);const qty=Number(i.quantity||0),landed=Number(i.landed_cost_per_unit_cad||0),sell=Number(i.target_sell_price_cad||0),rev=sell*qty,inv=landed*qty,margin=rev>0?(rev-inv)/rev*100:null,min=moqNumber(i.moq_text),below=min!==null&&qty<min;return <tr key={i.id}><td style={{padding:9,borderBottom:`1px solid ${C.border}`,fontFamily:"monospace",fontWeight:850,color:C.oliveDark}}>{p?.sku_id}</td><td style={{padding:9,borderBottom:`1px solid ${C.border}`}}>{p?.name}</td><td style={{padding:9,borderBottom:`1px solid ${C.border}`,color:below?C.red:C.ink,fontWeight:below?850:500}}>{qty}{below?" ⚠": ""}</td><td style={{padding:9,borderBottom:`1px solid ${C.border}`}}>{i.moq_text||"—"}</td><td style={{padding:9,borderBottom:`1px solid ${C.border}`}}>{usd(i.unit_price_usd)}</td><td style={{padding:9,borderBottom:`1px solid ${C.border}`}}>{money(i.landed_cost_per_unit_cad)}</td><td style={{padding:9,borderBottom:`1px solid ${C.border}`}}>{money(i.target_sell_price_cad)}</td><td style={{padding:9,borderBottom:`1px solid ${C.border}`}}>{money(inv)}</td><td style={{padding:9,borderBottom:`1px solid ${C.border}`}}>{money(rev)}</td><td style={{padding:9,borderBottom:`1px solid ${C.border}`,fontWeight:800,color:margin!==null&&margin<25?C.red:C.green}}>{margin===null?"—":`${margin.toFixed(1)}%`}</td><td style={{padding:9,borderBottom:`1px solid ${C.border}`}}><button style={btn()} onClick={()=>removeItem(i.id)}>Remove</button></td></tr>})}</tbody></table><div style={{fontSize:11,color:C.muted,marginTop:9}}>⚠ indicates quantity below the first numeric MOQ found in the supplier quote. PO item values are snapshots and do not change when the source quote changes later.</div></div>
            </>}
          </div>
        </div>
      </>}
    </div>
  </div>;
}
