import { useEffect, useMemo, useState } from "react";
import { calculateQuoteLandedCost } from "../domain/sourcingIntelligence";
import { buildDemandPlanning } from "../domain/demandPlanning";
import { loadDemandPlanningData, updateProductPlanning } from "../services/demandPlanningRepository";
import { addPurchaseOrderItem, createPurchaseOrder } from "../services/purchaseOrderRepository";

const num=(v,d=1)=>v==null||Number.isNaN(Number(v))?"—":Number(v).toLocaleString("en-CA",{maximumFractionDigits:d});
const date=v=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleDateString("en-CA",{year:"numeric",month:"short",day:"numeric"});};
const planningRef=()=>`PO-PLAN-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${String(Date.now()).slice(-5)}`;
const tone={"Needs Setup":"muted","No Sales History":"info",Healthy:"good",Plan:"info","Order Soon":"warn","Reorder Now":"bad","Stockout Risk":"bad"};

export default function MobileDemandPlanningWorkspace({onNavigate}){
  const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState("");
  const [search,setSearch]=useState(""),[filter,setFilter]=useState("All"),[drafts,setDrafts]=useState({}),[savingId,setSavingId]=useState(""),[creatingId,setCreatingId]=useState("");
  const load=async()=>{setLoading(true);setError("");try{const d=await loadDemandPlanningData();setData(d);setDrafts(Object.fromEntries(d.products.map(p=>[p.id,{leadTimeDays:p.planning_lead_time_days??"",safetyStockDays:String(p.safety_stock_days??14),orderCycleDays:String(p.order_cycle_days??30),preferredSupplierId:p.preferred_supplier_id||""}])));}catch(e){setError(e?.message||"Unable to load demand planning.");}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const analytics=useMemo(()=>data?buildDemandPlanning(data):null,[data]);
  const visible=useMemo(()=>{if(!analytics)return[];const q=search.trim().toLowerCase();return analytics.rows.filter(r=>{const match=!q||[r.product.sku_id,r.product.name,r.supplier?.name].filter(Boolean).some(v=>String(v).toLowerCase().includes(q));const f=filter==="All"||filter===r.status||(filter==="Actionable"&&["Stockout Risk","Reorder Now","Order Soon"].includes(r.status))||(filter==="Setup"&&r.status==="Needs Setup");return match&&f;});},[analytics,search,filter]);
  const save=async id=>{setSavingId(id);setError("");setMessage("");try{await updateProductPlanning(id,drafts[id]);await load();setMessage("Planning parameters saved.");}catch(e){setError(e?.message||"Unable to save planning parameters.");}finally{setSavingId("");}};
  const createDraft=async row=>{if(!row.canCreateDraft)return setError("A supplier quote, demand history and planning setup are required before creating a Buying Draft.");setCreatingId(row.product.id);setError("");setMessage("");try{const landed=calculateQuoteLandedCost(row.quote);const po=await createPurchaseOrder({poRef:planningRef(),supplierId:row.supplier.id,status:"Draft",orderDate:"",expectedDeliveryDate:"",currency:"USD",usdCadRate:row.quote.usd_cad_rate||1.38,incoterm:row.quote.incoterm||"",paymentTerms:"",notes:`Demand planning draft for ${row.product.sku_id}. Recommended order date ${date(row.reorderDate)}.`});await addPurchaseOrderItem({purchaseOrderId:po.id,productId:row.product.id,quoteId:row.quote.id,quantity:row.suggestedQty,moqText:row.quote.moq||null,supplierSku:row.quote.supplier_sku||null,unitPriceUsd:row.quote.unit_price??null,landedCostPerUnitCad:landed?.totalCad??null,targetSellPriceCad:row.product.target_sell_price_cad??row.product.market_reference_cad??null,notes:"Created from Demand Planning recommendation."});setMessage(`${po.po_ref} created as Draft.`);onNavigate?.("buying",{type:"reorder",poRef:po.po_ref,productSku:row.product.sku_id,quantity:row.suggestedQty});}catch(e){setError(e?.message||"Unable to create Buying Draft.");}finally{setCreatingId("");}};
  if(loading)return <div className="cg-mr-loading">Loading reorder plan…</div>;
  if(!analytics)return <div className="cg-mr-error">{error||"Unable to load demand planning."}</div>;
  const s=analytics.summary;
  return <div className="cg-mr-wrap">
    <div className="cg-mr-head"><div><div className="cg-mr-kicker">Business Insights</div><h2>Reorder</h2><p>Sales velocity, stock position and lead time in one mobile view.</p></div><button onClick={load}>Refresh</button></div>
    {error&&<div className="cg-mr-error">{error}</div>}{message&&<div className="cg-mr-success">{message}</div>}
    <div className="cg-mr-summary">{[['Actionable',s.actionableSkus],['Stockout Risk',s.stockoutRiskSkus],['Reorder Now',s.reorderNowSkus],['Suggested Units',num(s.suggestedUnits,0)]].map(([l,v])=><div key={l}><span>{l}</span><strong>{v}</strong></div>)}</div>
    <details className="cg-mr-method"><summary>How reorder works</summary><div><p>Demand uses active commercial orders. When both periods have sales, the daily rate weights the last 30 days at 60% and the last 90 days at 40%.</p><p><strong>No hidden lead-time assumption.</strong> Lead time is set per SKU. Safety stock defaults to 14 days and order cycle to 30 days, and both remain editable.</p></div></details>
    <div className="cg-mr-filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search SKU, product or supplier"/><select value={filter} onChange={e=>setFilter(e.target.value)}>{["All","Actionable","Stockout Risk","Reorder Now","Order Soon","Plan","Healthy","Setup","No Sales History"].map(x=><option key={x}>{x}</option>)}</select></div>
    <div className="cg-mr-list">{visible.map(row=>{const d=drafts[row.product.id]||{};return <article className="cg-mr-card" key={row.product.id}>
      <div className="cg-mr-card-top"><span>{row.product.sku_id}</span><em className={`cg-mr-badge ${tone[row.status]||"muted"}`}>{row.status}</em></div><h3>{row.product.name}</h3>
      <div className="cg-mr-metrics"><div><span>30d Sales</span><strong>{num(row.qty30,0)}</strong></div><div><span>90d Sales</span><strong>{num(row.qty90,0)}</strong></div><div><span>Available</span><strong>{num(row.available,0)}</strong></div><div><span>Inbound</span><strong>{num(row.inTransit,0)}</strong></div><div><span>Reorder Point</span><strong>{num(row.reorderPoint,0)}</strong></div><div><span>Suggested Qty</span><strong>{num(row.suggestedQty,0)}</strong></div></div>
      <div className="cg-mr-supplier"><span>Supplier</span><strong>{row.supplier?.name||"Not selected"}</strong><small>Reorder date {date(row.reorderDate)} · MOQ {row.quote?.moq||"—"}</small></div>
      <div className="cg-mr-fields"><label><span>Lead Time (days)</span><input type="number" min="0" value={d.leadTimeDays??""} onChange={e=>setDrafts(x=>({...x,[row.product.id]:{...d,leadTimeDays:e.target.value}}))}/></label><label><span>Safety Stock (days)</span><input type="number" min="0" value={d.safetyStockDays??""} onChange={e=>setDrafts(x=>({...x,[row.product.id]:{...d,safetyStockDays:e.target.value}}))}/></label><label><span>Order Cycle (days)</span><input type="number" min="1" value={d.orderCycleDays??""} onChange={e=>setDrafts(x=>({...x,[row.product.id]:{...d,orderCycleDays:e.target.value}}))}/></label><label><span>Preferred Supplier</span><select value={d.preferredSupplierId??""} onChange={e=>setDrafts(x=>({...x,[row.product.id]:{...d,preferredSupplierId:e.target.value}}))}><option value="">Not selected</option>{(data.suppliers||[]).map(sup=><option key={sup.id} value={sup.id}>{sup.sup_id} · {sup.name}</option>)}</select></label></div>
      <div className="cg-mr-actions"><button onClick={()=>save(row.product.id)} disabled={savingId===row.product.id}>{savingId===row.product.id?"Saving…":"Save Planning"}</button><button className="primary" onClick={()=>createDraft(row)} disabled={!row.canCreateDraft||creatingId===row.product.id}>{creatingId===row.product.id?"Creating…":row.canCreateDraft?"Create Buying Draft":"Setup / Quote Needed"}</button></div>
    </article>})}</div>
  </div>;
}
