import {useEffect,useMemo,useState} from "react";
import {supabase} from "../supabase";
import {addReceiptItem,createReceipt,deleteReceiptItem,listReceiptItems,listReceipts,loadPostedInventory,updateReceipt} from "../services/receivingRepository";
const C={ink:"#20251F",olive:"#858C38",green:"#4D7D57",red:"#B65145",muted:"#647062",border:"rgba(50,56,42,.12)",soft:"#F3F4EF"};
const input={width:"100%",boxSizing:"border-box",border:`1px solid ${C.border}`,borderRadius:10,padding:"9px 10px",fontSize:13,background:"#fff"};
const btn=p=>({border:p?0:`1px solid ${C.border}`,background:p?"#747B31":"#fff",color:p?"#fff":C.ink,borderRadius:10,padding:"9px 12px",fontWeight:800,cursor:"pointer"});
const money=v=>v==null?"N/A":Number(v).toLocaleString("en-CA",{style:"currency",currency:"CAD"});
const Field=({label,children})=><label style={{display:"grid",gap:5,fontSize:12,fontWeight:750,color:C.muted}}>{label}{children}</label>;
const ref=()=>`RCV-${new Date().toISOString().slice(0,10).replaceAll("-","")}`;
export default function ReceivingInventoryWorkspace(){
 const [receipts,setReceipts]=useState([]),[orders,setOrders]=useState([]),[poItems,setPoItems]=useState([]),[products,setProducts]=useState([]),[items,setItems]=useState([]),[inventoryRows,setInventoryRows]=useState([]),[selectedId,setSelectedId]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [form,setForm]=useState({receiptRef:ref(),purchaseOrderId:"",receivedDate:"",status:"Draft",location:"",notes:""});
 const [itemForm,setItemForm]=useState({purchaseOrderItemId:"",quantityReceived:"0",quantityDamaged:"0",quantityRejected:"0",actualLandedCostPerUnitCad:"",notes:""});
 const load=async()=>{try{const [r,{data:o,error:oe},{data:pi,error:pie},{data:p,error:pe},inv]=await Promise.all([listReceipts(),supabase.from("purchase_orders").select("*").order("created_at",{ascending:false}),supabase.from("purchase_order_items").select("*"),supabase.from("products").select("*").order("sku_id"),loadPostedInventory()]);if(oe||pie||pe)throw(oe||pie||pe);setReceipts(r);setOrders(o||[]);setPoItems(pi||[]);setProducts(p||[]);setInventoryRows(inv);}catch(e){setError(e.message||"Unable to load receiving data.");}};
 useEffect(()=>{load();},[]);
 useEffect(()=>{if(!selectedId){setItems([]);return;}const r=receipts.find(x=>x.id===selectedId);if(r)setForm({receiptRef:r.receipt_ref,purchaseOrderId:r.purchase_order_id,receivedDate:r.received_date||"",status:r.status,location:r.location||"",notes:r.notes||""});listReceiptItems(selectedId).then(setItems).catch(e=>setError(e.message));},[selectedId,receipts]);
 const orderItems=poItems.filter(i=>i.purchase_order_id===form.purchaseOrderId);
 const chosen=poItems.find(i=>i.id===itemForm.purchaseOrderItemId);
 useEffect(()=>{if(chosen)setItemForm(f=>({...f,actualLandedCostPerUnitCad:String(chosen.landed_cost_per_unit_cad??"")}));},[chosen]);
 const inventory=useMemo(()=>products.map(p=>{const rows=inventoryRows.filter(i=>i.product_id===p.id);const received=rows.reduce((s,i)=>s+Number(i.quantity_received||0),0),damaged=rows.reduce((s,i)=>s+Number(i.quantity_damaged||0),0),rejected=rows.reduce((s,i)=>s+Number(i.quantity_rejected||0),0);return{p,received,damaged,rejected,available:received-damaged-rejected};}).filter(x=>x.received>0),[products,inventoryRows]);
 const create=async()=>{if(!form.purchaseOrderId)return setError("Select a purchase order.");try{const r=await createReceipt(form);await load();setSelectedId(r.id);setMessage("Receiving record created as Draft.");}catch(e){setError(e.message);}};
 const save=async()=>{try{if(!selectedId)return create();await updateReceipt(selectedId,form);await load();setMessage(form.status==="Posted"?"Receipt posted. Accepted units are now included in inventory.":"Receipt updated.");}catch(e){setError(e.message);}};
 const add=async()=>{if(!selectedId||!chosen)return;const qr=Number(itemForm.quantityReceived||0),qd=Number(itemForm.quantityDamaged||0),qj=Number(itemForm.quantityRejected||0);if(qd+qj>qr)return setError("Damaged + rejected cannot exceed quantity received.");try{await addReceiptItem({receiptId:selectedId,purchaseOrderItemId:chosen.id,productId:chosen.product_id,...itemForm});setItems(await listReceiptItems(selectedId));setItemForm({purchaseOrderItemId:"",quantityReceived:"0",quantityDamaged:"0",quantityRejected:"0",actualLandedCostPerUnitCad:"",notes:""});setMessage("Received item recorded.");}catch(e){setError(e.message);}};
 return <div style={{minHeight:"100vh",background:C.soft,color:C.ink}}><div style={{background:"#20251F",color:"#fff",padding:"24px 32px"}}><div style={{maxWidth:1560,margin:"auto"}}><div style={{color:"#B6BE59",fontSize:12,fontWeight:850}}>COSTA GEAR</div><h1 style={{margin:"4px 0"}}>Receiving & Inventory</h1><div style={{color:"#C9CFC4",fontSize:13}}>Receive purchase orders, capture discrepancies and build traceable on-hand inventory.</div></div></div><div style={{maxWidth:1560,margin:"auto",padding:"22px 32px 44px",display:"grid",gap:16}}>
 {error&&<div style={{background:"#FFF1EF",color:C.red,padding:12,borderRadius:10}}>{error}</div>}{message&&<div style={{background:"#EDF7EE",color:C.green,padding:12,borderRadius:10}}>{message}</div>}
 <div style={{display:"grid",gridTemplateColumns:"300px 1fr",gap:16,alignItems:"start"}}><div style={{background:"#fff",border:`1px solid ${C.border}`,borderRadius:16,padding:14,display:"grid",gap:8}}><div style={{display:"flex",justifyContent:"space-between"}}><strong>Receipts</strong><button style={btn()} onClick={()=>{setSelectedId("");setItems([]);setForm({receiptRef:`${ref()}-${receipts.length+1}`,purchaseOrderId:"",receivedDate:"",status:"Draft",location:"",notes:""});}}>New</button></div>{receipts.map(r=><button key={r.id} style={{...btn(),textAlign:"left",borderColor:selectedId===r.id?C.olive:C.border}} onClick={()=>setSelectedId(r.id)}><b>{r.receipt_ref}</b><div style={{fontSize:11,color:C.muted}}>{r.status}</div></button>)}</div>
 <div style={{display:"grid",gap:16}}><div style={{background:"#fff",border:`1px solid ${C.border}`,borderRadius:16,padding:16}}><div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:10}}><Field label="Receipt Ref"><input style={input} value={form.receiptRef} disabled={!!selectedId} onChange={e=>setForm(f=>({...f,receiptRef:e.target.value}))}/></Field><Field label="Purchase Order"><select style={input} value={form.purchaseOrderId} disabled={!!selectedId} onChange={e=>setForm(f=>({...f,purchaseOrderId:e.target.value}))}><option value="">Select PO</option>{orders.map(o=><option key={o.id} value={o.id}>{o.po_ref} · {o.status}</option>)}</select></Field><Field label="Received Date"><input style={input} type="date" value={form.receivedDate} onChange={e=>setForm(f=>({...f,receivedDate:e.target.value}))}/></Field><Field label="Status"><select style={input} value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value}))}>{["Draft","Posted","Cancelled"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Location"><input style={input} value={form.location} placeholder="Home storage / Warehouse" onChange={e=>setForm(f=>({...f,location:e.target.value}))}/></Field><Field label="Notes"><input style={input} value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></Field></div><div style={{marginTop:12}}><button style={btn(true)} onClick={save}>{selectedId?"Save Receipt":"Create Draft"}</button></div></div>
 {selectedId&&<><div style={{background:"#fff",border:`1px solid ${C.border}`,borderRadius:16,padding:16}}><strong>Record PO Item</strong><div style={{display:"grid",gridTemplateColumns:"2fr repeat(4,1fr) auto",gap:8,alignItems:"end",marginTop:10}}><Field label="PO Item"><select style={input} value={itemForm.purchaseOrderItemId} onChange={e=>setItemForm(f=>({...f,purchaseOrderItemId:e.target.value}))}><option value="">Select item</option>{orderItems.map(i=>{const p=products.find(x=>x.id===i.product_id);return <option key={i.id} value={i.id}>{p?.sku_id} · ordered {i.quantity}</option>})}</select></Field><Field label="Received"><input style={input} type="number" min="0" value={itemForm.quantityReceived} onChange={e=>setItemForm(f=>({...f,quantityReceived:e.target.value}))}/></Field><Field label="Damaged"><input style={input} type="number" min="0" value={itemForm.quantityDamaged} onChange={e=>setItemForm(f=>({...f,quantityDamaged:e.target.value}))}/></Field><Field label="Rejected"><input style={input} type="number" min="0" value={itemForm.quantityRejected} onChange={e=>setItemForm(f=>({...f,quantityRejected:e.target.value}))}/></Field><Field label="Actual Landed / Unit"><input style={input} type="number" min="0" step="0.01" value={itemForm.actualLandedCostPerUnitCad} onChange={e=>setItemForm(f=>({...f,actualLandedCostPerUnitCad:e.target.value}))}/></Field><button style={btn(true)} onClick={add}>Add</button></div></div>
 <div style={{background:"#fff",border:`1px solid ${C.border}`,borderRadius:16,padding:16,overflowX:"auto"}}><strong>Receipt Lines</strong><table style={{width:"100%",borderCollapse:"collapse",marginTop:10,fontSize:12}}><thead><tr>{["SKU","Ordered","Received","Damaged","Rejected","Available","Planned Landed","Actual Landed","Variance",""].map(h=><th key={h} style={{textAlign:"left",padding:8,borderBottom:`1px solid ${C.border}`}}>{h}</th>)}</tr></thead><tbody>{items.map(i=>{const poi=poItems.find(x=>x.id===i.purchase_order_item_id),p=products.find(x=>x.id===i.product_id),available=Number(i.quantity_received)-Number(i.quantity_damaged)-Number(i.quantity_rejected),planned=poi?.landed_cost_per_unit_cad,actual=i.actual_landed_cost_per_unit_cad,variance=planned!=null&&actual!=null?Number(actual)-Number(planned):null;return <tr key={i.id}>{[p?.sku_id,poi?.quantity,i.quantity_received,i.quantity_damaged,i.quantity_rejected,available,money(planned),money(actual),variance==null?"N/A":money(variance)].map((v,n)=><td key={n} style={{padding:8,borderBottom:`1px solid ${C.border}`}}>{v}</td>)}<td><button style={btn()} onClick={async()=>{await deleteReceiptItem(i.id);setItems(await listReceiptItems(selectedId));}}>Remove</button></td></tr>})}</tbody></table></div></>}
 </div></div>
 <div style={{background:"#fff",border:`1px solid ${C.border}`,borderRadius:16,padding:16,overflowX:"auto"}}><h2 style={{margin:"0 0 4px"}}>On-hand Inventory</h2><div style={{fontSize:12,color:C.muted,marginBottom:10}}>Only Posted receipts count. Available = received minus damaged minus rejected.</div><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{["SKU","Product","Received","Damaged","Rejected","Available"].map(h=><th key={h} style={{textAlign:"left",padding:8,borderBottom:`1px solid ${C.border}`}}>{h}</th>)}</tr></thead><tbody>{inventory.map(x=><tr key={x.p.id}>{[x.p.sku_id,x.p.name,x.received,x.damaged,x.rejected,x.available].map((v,n)=><td key={n} style={{padding:8,borderBottom:`1px solid ${C.border}`,fontWeight:n===5?850:400}}>{v}</td>)}</tr>)}</tbody></table>{!inventory.length&&<div style={{padding:24,textAlign:"center",color:C.muted}}>No posted inventory yet.</div>}</div>
 </div></div>;
}