import { supabase } from "../supabase";

const fail=(error)=>{if(error)throw error;};
export async function listReceipts(){const {data,error}=await supabase.from("receipts").select("*").order("created_at",{ascending:false});fail(error);return data||[];}
export async function listReceiptItems(receiptId){const {data,error}=await supabase.from("receipt_items").select("*").eq("receipt_id",receiptId).order("created_at");fail(error);return data||[];}
export async function createReceipt(v){const {data,error}=await supabase.from("receipts").insert({receipt_ref:v.receiptRef,purchase_order_id:v.purchaseOrderId,received_date:v.receivedDate||null,status:v.status||"Draft",location:v.location||null,notes:v.notes||null}).select().single();fail(error);return data;}
export async function updateReceipt(id,v){const {data,error}=await supabase.from("receipts").update({received_date:v.receivedDate||null,status:v.status,location:v.location||null,notes:v.notes||null,updated_at:new Date().toISOString()}).eq("id",id).select().single();fail(error);return data;}
export async function addReceiptItem(v){const {data,error}=await supabase.from("receipt_items").insert({receipt_id:v.receiptId,purchase_order_item_id:v.purchaseOrderItemId,product_id:v.productId,quantity_received:Number(v.quantityReceived||0),quantity_damaged:Number(v.quantityDamaged||0),quantity_rejected:Number(v.quantityRejected||0),actual_landed_cost_per_unit_cad:v.actualLandedCostPerUnitCad===""||v.actualLandedCostPerUnitCad==null?null:Number(v.actualLandedCostPerUnitCad),notes:v.notes||null}).select().single();fail(error);return data;}
export async function deleteReceiptItem(id){const {error}=await supabase.from("receipt_items").delete().eq("id",id);fail(error);}
export async function loadPostedInventory(){const {data:r,error:re}=await supabase.from("receipts").select("id,status").eq("status","Posted");fail(re);const ids=(r||[]).map(x=>x.id);if(!ids.length)return[];const {data,error}=await supabase.from("receipt_items").select("*").in("receipt_id",ids);fail(error);return data||[];}
