import { supabase } from "../supabase";

export async function listShipments(){const {data,error}=await supabase.from("shipments").select("*").order("created_at",{ascending:false});if(error)throw error;return data||[];}
export async function createShipment(record){const row={shipment_ref:record.shipmentRef,purchase_order_id:record.purchaseOrderId||null,supplier_id:record.supplierId||null,status:record.status||"Planning",shipping_method:record.shippingMethod||null,freight_amount:Number(record.freightAmount||0),freight_currency:record.freightCurrency||"USD",usd_cad_rate:Number(record.usdCadRate||1.38),allocation_method:record.allocationMethod||"weight",brokerage_amount:Number(record.brokerageAmount||0),brokerage_currency:record.brokerageCurrency||"CAD",other_import_costs_amount:Number(record.otherImportCostsAmount||0),other_import_costs_currency:record.otherImportCostsCurrency||"CAD",import_allocation_method:record.importAllocationMethod||"value",notes:record.notes||null};const {data,error}=await supabase.from("shipments").insert(row).select("*").single();if(error)throw error;return data;}
export async function createShipmentFromPO(record){const {data,error}=await supabase.rpc("create_shipment_from_po",{p_purchase_order_id:record.purchaseOrderId,p_status:record.status||"Planning",p_shipping_method:record.shippingMethod||null,p_freight_amount:Number(record.freightAmount||0),p_freight_currency:record.freightCurrency||"USD",p_usd_cad_rate:Number(record.usdCadRate),p_allocation_method:record.allocationMethod||"weight",p_notes:record.notes||null});if(error)throw error;return data;}
export async function updateShipment(id,record){const row={};if("purchaseOrderId" in record)row.purchase_order_id=record.purchaseOrderId||null;if("supplierId" in record)row.supplier_id=record.supplierId||null;if("status" in record)row.status=record.status;if("shippingMethod" in record)row.shipping_method=record.shippingMethod||null;if("freightAmount" in record)row.freight_amount=Number(record.freightAmount||0);if("freightCurrency" in record)row.freight_currency=record.freightCurrency||"USD";if("usdCadRate" in record)row.usd_cad_rate=Number(record.usdCadRate);if("allocationMethod" in record)row.allocation_method=record.allocationMethod||"weight";if("brokerageAmount" in record)row.brokerage_amount=Number(record.brokerageAmount||0);if("brokerageCurrency" in record)row.brokerage_currency=record.brokerageCurrency||"CAD";if("otherImportCostsAmount" in record)row.other_import_costs_amount=Number(record.otherImportCostsAmount||0);if("otherImportCostsCurrency" in record)row.other_import_costs_currency=record.otherImportCostsCurrency||"CAD";if("importAllocationMethod" in record)row.import_allocation_method=record.importAllocationMethod||"value";if("notes" in record)row.notes=record.notes||null;if(!Object.keys(row).length)throw new Error("No shipment fields were provided to update.");const {data,error}=await supabase.from("shipments").update(row).eq("id",id).select("*").single();if(error)throw error;return data;}
export async function listShipmentItems(shipmentId){const {data,error}=await supabase.from("shipment_items").select("*").eq("shipment_id",shipmentId).order("created_at");if(error)throw error;return data||[];}
export async function addShipmentItem(record){const row={shipment_id:record.shipmentId,purchase_order_item_id:record.purchaseOrderItemId||null,product_id:record.productId,quote_id:record.quoteId||null,quantity:Number(record.quantity||1),manual_allocation_cad:record.manualAllocationCad===""||record.manualAllocationCad==null?null:Number(record.manualAllocationCad),duty_rate_pct:record.dutyRatePct===""||record.dutyRatePct==null?null:Number(record.dutyRatePct),manual_brokerage_cad:record.manualBrokerageCad===""||record.manualBrokerageCad==null?null:Number(record.manualBrokerageCad),manual_other_import_cad:record.manualOtherImportCad===""||record.manualOtherImportCad==null?null:Number(record.manualOtherImportCad),notes:record.notes||null};const {data,error}=await supabase.from("shipment_items").insert(row).select("*").single();if(error)throw error;return data;}
export async function updateShipmentItem(id,record){const row={};if("quantity" in record)row.quantity=Number(record.quantity||1);if("quoteId" in record)row.quote_id=record.quoteId||null;if("manualAllocationCad" in record)row.manual_allocation_cad=record.manualAllocationCad===""||record.manualAllocationCad==null?null:Number(record.manualAllocationCad);if("allocatedFreightCad" in record)row.allocated_shipping_cad=record.allocatedFreightCad==null?null:Number(record.allocatedFreightCad);if("allocationBasis" in record)row.allocation_basis=record.allocationBasis==null?null:Number(record.allocationBasis);if("dutyRatePct" in record)row.duty_rate_pct=record.dutyRatePct===""||record.dutyRatePct==null?null:Number(record.dutyRatePct);if("manualBrokerageCad" in record)row.manual_brokerage_cad=record.manualBrokerageCad===""||record.manualBrokerageCad==null?null:Number(record.manualBrokerageCad);if("manualOtherImportCad" in record)row.manual_other_import_cad=record.manualOtherImportCad===""||record.manualOtherImportCad==null?null:Number(record.manualOtherImportCad);if("allocatedBrokerageCad" in record)row.allocated_brokerage_cad=record.allocatedBrokerageCad==null?null:Number(record.allocatedBrokerageCad);if("allocatedBrokeragePerUnitCad" in record)row.allocated_brokerage_per_unit_cad=record.allocatedBrokeragePerUnitCad==null?null:Number(record.allocatedBrokeragePerUnitCad);if("allocatedOtherImportCad" in record)row.allocated_other_import_cad=record.allocatedOtherImportCad==null?null:Number(record.allocatedOtherImportCad);if("allocatedOtherImportPerUnitCad" in record)row.allocated_other_import_per_unit_cad=record.allocatedOtherImportPerUnitCad==null?null:Number(record.allocatedOtherImportPerUnitCad);if("notes" in record)row.notes=record.notes||null;const {data,error}=await supabase.from("shipment_items").update(row).eq("id",id).select("*").single();if(error)throw error;return data;}
export async function deleteShipmentItem(id){const {error}=await supabase.from("shipment_items").delete().eq("id",id);if(error)throw error;}
export async function applyShipmentFreight(shipmentId){const {data,error}=await supabase.rpc("apply_shipment_freight",{p_shipment_id:shipmentId});if(error)throw error;return data;}
export async function applyAllocationToQuotes(rows){const shipmentId=rows?.find(r=>r.shipment_id)?.shipment_id;if(!shipmentId)throw new Error("Shipment ID is required to apply freight.");return applyShipmentFreight(shipmentId);}
export async function applyShipmentImportCosts(shipmentId){const {data,error}=await supabase.rpc("apply_shipment_import_costs",{p_shipment_id:shipmentId});if(error)throw error;return data;}
export async function applyImportCostsToQuotes(rows){const shipmentId=rows?.find(r=>r.shipment_id)?.shipment_id;if(!shipmentId)throw new Error("Shipment ID is required to apply import costs.");return applyShipmentImportCosts(shipmentId);}
