import { supabase } from "../supabase";

export async function listShipments(){const {data,error}=await supabase.from("shipments").select("*").order("created_at",{ascending:false});if(error)throw error;return data||[];}
export async function createShipment(record){const row={shipment_ref:record.shipmentRef,purchase_order_id:record.purchaseOrderId||null,supplier_id:record.supplierId||null,status:record.status||"Planning",shipping_method:record.shippingMethod||null,freight_amount:Number(record.freightAmount||0),freight_currency:record.freightCurrency||"USD",usd_cad_rate:Number(record.usdCadRate||1.38),allocation_method:record.allocationMethod||"weight",brokerage_amount:Number(record.brokerageAmount||0),brokerage_currency:record.brokerageCurrency||"CAD",other_import_costs_amount:Number(record.otherImportCostsAmount||0),other_import_costs_currency:record.otherImportCostsCurrency||"CAD",import_allocation_method:record.importAllocationMethod||"value",notes:record.notes||null};const {data,error}=await supabase.from("shipments").insert(row).select("*").single();if(error)throw error;return data;}
export async function createShipmentFromPO(record){const {data,error}=await supabase.rpc("create_shipment_from_po",{p_purchase_order_id:record.purchaseOrderId,p_status:record.status||"Planning",p_shipping_method:record.shippingMethod||null,p_freight_amount:Number(record.freightAmount||0),p_freight_currency:record.freightCurrency||"USD",p_usd_cad_rate:Number(record.usdCadRate),p_allocation_method:record.allocationMethod||"weight",p_notes:record.notes||null});if(error)throw error;return data;}
export async function updateShipment(id,record){const row={purchase_order_id:record.purchaseOrderId||null,supplier_id:record.supplierId||null,status:record.status,shipping_method:record.shippingMethod||null,freight_amount:Number(record.freightAmount||0),freight_currency:record.freightCurrency||"USD",usd_cad_rate:Number(record.usdCadRate||1.38),allocation_method:record.allocationMethod||"weight",brokerage_amount:Number(record.brokerageAmount||0),brokerage_currency:record.brokerageCurrency||"CAD",other_import_costs_amount:Number(record.otherImportCostsAmount||0),other_import_costs_currency:record.otherImportCostsCurrency||"CAD",import_allocation_method:record.importAllocationMethod||"value",notes:record.notes||null};const {data,error}=await supabase.from("shipments").update(row).eq("id",id).select("*").single();if(error)throw error;return data;}
export async function listShipmentItems(shipmentId){const {data,error}=await supabase.from("shipment_items").select("*").eq("shipment_id",shipmentId).order("created_at");if(error)throw error;return data||[];}
export async function addShipmentItem(record){const row={shipment_id:record.shipmentId,purchase_order_item_id:record.purchaseOrderItemId||null,product_id:record.productId,quote_id:record.quoteId||null,quantity:Number(record.quantity||1),manual_allocation_cad:record.manualAllocationCad===""||record.manualAllocationCad==null?null:Number(record.manualAllocationCad),duty_rate_pct:record.dutyRatePct===""||record.dutyRatePct==null?null:Number(record.dutyRatePct),manual_brokerage_cad:record.manualBrokerageCad===""||record.manualBrokerageCad==null?null:Number(record.manualBrokerageCad),manual_other_import_cad:record.manualOtherImportCad===""||record.manualOtherImportCad==null?null:Number(record.manualOtherImportCad),notes:record.notes||null};const {data,error}=await supabase.from("shipment_items").insert(row).select("*").single();if(error)throw error;return data;}
export async function updateShipmentItem(id,record){const row={quantity:Number(record.quantity||1),quote_id:record.quoteId||null,manual_allocation_cad:record.manualAllocationCad===""||record.manualAllocationCad==null?null:Number(record.manualAllocationCad),allocated_shipping_cad:record.allocatedFreightCad==null?null:Number(record.allocatedFreightCad),allocation_basis:record.allocationBasis==null?null:Number(record.allocationBasis),duty_rate_pct:record.dutyRatePct===""||record.dutyRatePct==null?null:Number(record.dutyRatePct),manual_brokerage_cad:record.manualBrokerageCad===""||record.manualBrokerageCad==null?null:Number(record.manualBrokerageCad),manual_other_import_cad:record.manualOtherImportCad===""||record.manualOtherImportCad==null?null:Number(record.manualOtherImportCad),allocated_brokerage_cad:record.allocatedBrokerageCad==null?null:Number(record.allocatedBrokerageCad),allocated_brokerage_per_unit_cad:record.allocatedBrokeragePerUnitCad==null?null:Number(record.allocatedBrokeragePerUnitCad),allocated_other_import_cad:record.allocatedOtherImportCad==null?null:Number(record.allocatedOtherImportCad),allocated_other_import_per_unit_cad:record.allocatedOtherImportPerUnitCad==null?null:Number(record.allocatedOtherImportPerUnitCad),notes:record.notes||null};const {data,error}=await supabase.from("shipment_items").update(row).eq("id",id).select("*").single();if(error)throw error;return data;}
export async function deleteShipmentItem(id){const {error}=await supabase.from("shipment_items").delete().eq("id",id);if(error)throw error;}
export async function applyShipmentFreight(shipmentId){const {data,error}=await supabase.rpc("apply_shipment_freight",{p_shipment_id:shipmentId});if(error)throw error;return data;}
export async function applyAllocationToQuotes(rows){for(const row of rows){if(!row.quote_id)continue;const {error}=await supabase.from("quotes").update({shipping_cost_per_unit_cad:Number(row.perUnitCad.toFixed(2)),shipping_allocation_method:row.allocationMethod||null,shipping_cost_basis:"shipment_allocation",landed_cost_cad:null}).eq("id",row.quote_id);if(error)throw error;}}
export async function applyImportCostsToQuotes(rows){for(const row of rows){if(!row.quote_id)continue;const payload={brokerage_cad:Number((row.brokeragePerUnitCad||0).toFixed(2)),other_fees_cad:Number((row.otherPerUnitCad||0).toFixed(2)),landed_cost_cad:null};if(row.duty_rate_pct!==null&&row.duty_rate_pct!==undefined&&row.duty_rate_pct!=="")payload.duty_rate_pct=Number(row.duty_rate_pct);const {error}=await supabase.from("quotes").update(payload).eq("id",row.quote_id);if(error)throw error;}}
